server:
  port: 8504

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: consul
          uri: lb://service-consulDemo
          predicates:
            - Path=/consul/**
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

