server:
  port: 8504

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - uri: https://www.baidu.com
          predicates:
            - Path=/consul
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-gateway

