server:
  port: 8503

spring:
  application:
    name: service-consulDemo
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #已ip形式注册到consul
        prefer-ip-address: true
  redis:
    host: 123.207.23.223
    port: 6379
    password: 319812
